apiVersion: 1
datasources: # tell Grafana to load these datasources on startup
  - name: Prometheus
    type: prometheus
    uid: prom
    url: http://prometheus:9090
    isDefault: true

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200

#traces and metrics no logs yet